# Generated by Django 3.2.6 on 2021-08-24 11:07

from django.db import migrations, models
import imagekit.models.fields
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMoudel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedAt', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100)),
                ('orderNumber', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=report.models.report_upload_location)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['title'],
            },
        ),
    ]
