# Generated by Django 3.1.1 on 2021-07-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='orderId',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.TextField(default='none'),
        ),
    ]
