# Generated by Django 2.1.15 on 2021-05-23 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Erfarenhet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('plats', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('started_at', models.CharField(max_length=100, verbose_name='started at')),
                ('ended_at', models.CharField(max_length=100, verbose_name='ended at')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Erfarenhet',
                'verbose_name_plural': 'Erfarenhets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Intressen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intressen',
                'verbose_name_plural': 'Intressens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kompetenser_intyg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kompetenser eller intyg',
                'verbose_name_plural': 'Kompetensers och intygs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('plats', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('started_at', models.CharField(max_length=100, verbose_name='started at')),
                ('ended_at', models.CharField(max_length=100, verbose_name='ended at')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Studier',
                'verbose_name_plural': 'Studiers',
                'ordering': ['name'],
            },
        ),
    ]
