# Generated by Django 2.2 on 2021-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='ordered_at')),
                ('customerIdd', models.CharField(max_length=50)),
                ('employedIdd', models.CharField(max_length=50)),
                ('serviceId', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('enhet', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('pend', 'Pend'), ('payed', 'Payed')], default='requested', max_length=10, verbose_name='Status of service:')),
            ],
        ),
    ]
