# Generated by Django 2.2 on 2021-07-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0002_serviceorder_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='thread',
        ),
    ]
