# Generated by Django 3.2.6 on 2021-08-20 22:41

import Service.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('img', imagekit.models.fields.ProcessedImageField(blank=True, default='CategoryDefaultImage.jpg', upload_to=Service.models.cat_upload_location)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('stripeId', models.CharField(blank=True, max_length=200, null=True)),
                ('site_id', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('pris', models.IntegerField()),
                ('bedomning', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('beskrivning', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='Is published?')),
                ('tillganligFran', models.DateTimeField(default=django.utils.timezone.now)),
                ('tillganligTill', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', imagekit.models.fields.ProcessedImageField(default='ServiceDefaultImage.jpg', upload_to=Service.models.upload_location)),
                ('image2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=Service.models.upload_location)),
                ('image3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=Service.models.upload_location)),
                ('image4', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=Service.models.upload_location)),
                ('image5', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=Service.models.upload_location)),
                ('category', models.CharField(blank=True, max_length=1024, null=True)),
                ('enhet', models.CharField(blank=True, max_length=30, null=True)),
                ('underCategory', models.CharField(blank=True, max_length=1024, null=True)),
                ('country', models.CharField(blank=True, max_length=1024, null=True, verbose_name='contry')),
                ('state', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Lansting')),
                ('city', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Kommun')),
                ('AboutSeller', models.CharField(blank=True, max_length=1024, null=True, verbose_name='AboutSeller')),
                ('sellerName', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Seller name')),
                ('expiration_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 20, 0, 41, 32, 790619), null=True)),
                ('disLikes', models.ManyToManyField(blank=True, related_name='post_disLikes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updatedAt',),
            },
        ),
        migrations.CreateModel(
            name='ModelSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Under category')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.modelcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ModelState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.modelcountry')),
            ],
        ),
        migrations.CreateModel(
            name='ModelComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1024, verbose_name='Seller name')),
                ('postNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.servicepost')),
            ],
        ),
    ]
