# Generated by Django 3.2.6 on 2021-08-20 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 20, 0, 41, 52, 85521), null=True),
        ),
    ]
