# Generated by Django 3.2.6 on 2021-08-21 00:53

import Service.models
import datetime
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_servicepost_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 20, 2, 53, 35, 702502), null=True),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Service.models.upload_location),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Service.models.upload_location),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Service.models.upload_location),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Service.models.upload_location),
        ),
    ]
