# Generated by Django 3.2.6 on 2021-08-24 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_auto_20210821_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 23, 13, 7, 19, 238445), null=True),
        ),
    ]
