# Generated by Django 3.2.6 on 2021-08-24 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_alter_servicepost_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 23, 15, 55, 19, 702093), null=True),
        ),
    ]
