# Generated by Django 2.2 on 2021-05-25 10:23

from django.db import migrations, models
import home.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContainersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('img_x_large', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=home.models.Home_upload_location)),
            ],
            options={
                'verbose_name': 'Home container',
                'verbose_name_plural': 'Home containers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomeSliderMoudel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('img_x_large', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=home.models.Home_upload_location)),
            ],
            options={
                'verbose_name': 'Home slider',
                'verbose_name_plural': 'Home sliders',
                'ordering': ['name'],
            },
        ),
    ]
